In [6]:
import numpy as np

array_1boyut = np.array([1, 2, 3, 4, 5], dtype=int)
print("Bir boyutlu array:", array_1boyut)
print("Boyut:", array_1boyut.ndim)
print("Eleman sayısı:", array_1boyut.size)
print("Şekil (shape):", array_1boyut.shape)
print()

Bir boyutlu array: [1 2 3 4 5]
Boyut: 1
Eleman sayısı: 5
Şekil (shape): (5,)



In [7]:
array_2boyut = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print("İki boyutlu array:\n", array_2boyut)
print("Boyut:", array_2boyut.ndim)
print("Eleman sayısı:", array_2boyut.size)
print("Şekil (shape):", array_2boyut.shape)
print("Satır sayısı:", array_2boyut.shape[0])
print("Sütun sayısı:", array_2boyut.shape[1])
print()

İki boyutlu array:
 [[1 2 3]
 [4 5 6]]
Boyut: 2
Eleman sayısı: 6
Şekil (shape): (2, 3)
Satır sayısı: 2
Sütun sayısı: 3



In [8]:
array_3boyut = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=int)
print("Üç boyutlu array:\n", array_3boyut)
print("Boyut:", array_3boyut.ndim)
print("Eleman:", array_3boyut.size)
print("Şekil:", array_3boyut.shape)
print("Katman:", array_3boyut.shape[0])
print("Satır:", array_3boyut.shape[1])
print("Sütun:", array_3boyut.shape[2])
print()

Üç boyutlu array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Boyut: 3
Eleman: 8
Şekil: (2, 2, 2)
Katman: 2
Satır: 2
Sütun: 2



In [9]:
print("İki boyutlu arrayde 1. satır:", array_2boyut[0]) 
print("İki boyutlu arrayde [1,1] indexindeki eleman:", array_2boyut[1, 1])
print("İki boyutlu arrayin ilk iki sütunu:\n", array_2boyut[:, :2])
print()

print("Üç boyutlu arrayin ilk katmanı:\n", array_3boyut[0])  
print("Üç boyutlu arrayin [1,0,1] indexindeki eleman:", array_3boyut[1, 0, 1])
print()

İki boyutlu arrayde 1. satır: [1 2 3]
İki boyutlu arrayde [1,1] indexindeki eleman: 5
İki boyutlu arrayin ilk iki sütunu:
 [[1 2]
 [4 5]]

Üç boyutlu arrayin ilk katmanı:
 [[1 2]
 [3 4]]
Üç boyutlu arrayin [1,0,1] indexindeki eleman: 6



In [10]:
zeros_array = np.zeros((2, 3), dtype=int)
ones_array = np.ones((2, 3), dtype=int)

print("Sıfır array:\n", zeros_array)
print("Bir array:\n", ones_array)
print()

satir= np.vstack((zeros_array, ones_array)) 
sutun= np.hstack((zeros_array, ones_array))  

print("Satır birleştir:\n", satir)
print("Sütun birleştir:\n", sutun)

Sıfır array:
 [[0 0 0]
 [0 0 0]]
Bir array:
 [[1 1 1]
 [1 1 1]]

Satır birleştir:
 [[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]
Sütun birleştir:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
